# Generated by Django 4.0.1 on 2022-01-10 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('code_product', models.CharField(max_length=15, unique=True, verbose_name='Código')),
                ('description_product', models.CharField(max_length=80, verbose_name='Principio y Concentración')),
                ('pharma_form', models.CharField(choices=[('Tableta', 'Tableta'), ('Capsula', 'Capsula'), ('Granulado', 'Granulado'), ('Supositorio', 'Supositorio'), ('Polvo para Reconstituir', 'Polvo para Reconstituir'), ('Crema', 'Crema'), ('Unguento', 'Unguento'), ('Pasta', 'Pasta'), ('Emulsión', 'Emulsión'), ('Gel', 'Gel'), ('Jarabe', 'Jarabe'), ('Suspensión', 'Suspensión'), ('Elixir', 'Elixir'), ('Solución', 'Solución')], max_length=80, verbose_name='Forma Farmacéutica')),
                ('presentation_prod', models.CharField(max_length=80, verbose_name='Presentación')),
                ('brand_product', models.CharField(max_length=80, verbose_name='Nombre Comercial')),
                ('sanitary_license', models.CharField(max_length=80, verbose_name='Registro Sanitario')),
                ('product_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
            },
        ),
    ]
