# Generated by Django 3.2.7 on 2021-09-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210918_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='user/%Y%m%d', verbose_name='Foto'),
        ),
    ]
